- 👋 Hi, I’m @Wijdane-Tech
- 👀 I’m interested in AI tools
- 🌱 I’m currently learning the basics of computer science
- 💞️ I’m looking to collaborate on a project for beginners
- 📫 How to reach me : telegram @Wijjdane
- ⚡ Fun fact: I Only code with excel VBA to automate my tasks at work
